### ISSUE TITLE
what dose @ mean?

### ISSUE THREAD

**Issue by Chuan-Chuan-Chuan** [sfschouten/egnn#1]

**Comment by sfschouten** [comment]
Hi, 

The @ symbol in python is the matrix multiplication operator. https://legacy.python.org/dev/peps/pep-0465/
When used with PyTorch tensors, A@B is equivalent to torch.matmul(A, B)

Hope this helps,
Stefan

PS the code in this repo is not tested, I got stuck on something so I never really finished it. Please take it with a grain of salt.

**Comment by Chuan-Chuan-Chuan** [comment]
Thanks for your reply. Your code helps me a lot. Thanks again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sfschouten/egnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 下午3:09
收件人:&nbsp;"sfschouten/egnn"<egnn@noreply.github.com&gt;;
抄送:&nbsp;"D"<449228921@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sfschouten/egnn] what dose @ mean? (#1)





 
Hi,
 
The @ symbol in python is the matrix multiplication operator. https://legacy.python.org/dev/peps/pep-0465/
 When used with PyTorch tensors, A@B is equivalent to torch.matmul(A, B)
 
Hope this helps,
 Stefan
 
PS the code in this repo is not tested, I got stuck on something so I never really finished it. Please take it with a grain of salt.
